import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>hakusingo about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className='my-[2rem] flex justify-center'>
          <Image className="rounded-full w-[90%] h-[90%] max-h-[400px] max-w-[400px] object-cover" width="300" height="300" src="/my-image.jpg" alt="image description"/>
        </div>
        <div className="w-3/4 mx-auto">
          <p className="mb-3 font-light text-gray-500 dark:text-gray-400 first-line:uppercase first-line:tracking-widest first-letter:text-7xl first-letter:font-bold first-letter:text-gray-900 dark:first-letter:text-gray-100 first-letter:mr-3 first-letter:float-left">沖縄県うるま市具志川生まれ、具志川育ち。バスケットボール、読書、散歩、音楽（何でも聞く）PCいじり、プログラミングが大好きの1983年生まれ。
２０代のころ東京(新小岩・吉祥寺)に10年ほど住む、飲食店スタッフ・バーテンダー、お寺で働いた後に地元のウェブ系の会社で働く。</p>
          <p className="font-light text-gray-500 dark:text-gray-400">2022年より独立。ウェブサイト制作やアプリ開発・ウェブライティングなどITの知識を生かして、地元でお困りの方の手助けをするウェブ屋さん。</p>
        </div>
      </main>
    </Layout>
  )
}
