import Head from 'next/head'

import Layout from '../components/layout'
import Hero from '@/components/index/hero'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>hakusingo portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Hero />
      </main>
    </Layout>
  )
}
